package org.metagene.genestrip.service.jdbc;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import javax.sql.DataSource;

import org.metagene.genestrip.service.InstallService;
import org.metagene.genestrip.service.ServiceException;

public class InstallJDBCService extends AbstractJDBCService implements InstallService {
	public InstallJDBCService(DataSource dataSource) {
		super(dataSource);
	}

	@Override
	public void install() {
		Connection c = null;
		try {
			c = getConnection();
			
			Statement s = c.createStatement();
			s.execute(
					"create table if not exists person (id bigint not null primary key generated by default as identity, first_name varchar(255), last_name varchar(255))");
			s.execute(
					"create table if not exists sysuser (id bigint not null primary key generated by default as identity, login varchar(50) unique not null, password varchar(50) not null, allow_all boolean not null, allow_jobs boolean not null, person_id bigint not null, constraint fk_person_id foreign key(person_id) references person(id) on update cascade on delete cascade)");
			s.execute(
					"create table if not exists db (id bigint not null primary key generated by default as identity, name varchar(255) unique not null, db_file_prefix varchar(255) unique not null)");
			s.execute(
					"create table if not exists job (id bigint not null primary key generated by default as identity, name varchar(255) not null, fastq_file varchar(255) not null, fastq_file_2 varchar(255), db_id bigint not null, user_id bigint not null, status int not null, enqueued datetime, started datetime, finished datetime, constraint fk_db_id foreign key(db_id) references db(id) on update cascade on delete cascade, constraint fk_user_id foreign key(user_id) references sysuser(id) on update cascade on delete cascade)");

		} catch (SQLException e) {
			throw new ServiceException(e);
		} finally {
			releaseConnection(c);
		}
	}
}
